/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.70
 * Generated at: 2018-01-12 06:49:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class generateByEmail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"index.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/icon?family=Material+Icons\">\r\n");
      out.write("<style>\r\n");
      out.write("form {\r\n");
      out.write("\tpadding: 150px;\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("\tcolor: #1287A8;\r\n");
      out.write("\tfont-size: 25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".inputBox {\r\n");
      out.write("\tpadding: 5px;\r\n");
      out.write("\talign: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\tbackground-repeat: no-repeat;\r\n");
      out.write("\tbackground-size: cover;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#subtn {\r\n");
      out.write("\tfont-size: 16px;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\toutline: none;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tpadding: 14px 16px;\r\n");
      out.write("\tbackground-color:blue;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body background=\"virtual.jpg\">\r\n");
      out.write("<div class=\"navbar\">\r\n");
      out.write("\t\t<a href=\"index.html\">Home</a>\r\n");
      out.write("\t\t<div class=\"dropdown\">\r\n");
      out.write("\t\t\t<button class=\"dropbtn\">\r\n");
      out.write("\t\t\t\tAdd Test <i class=\"fa fa-caret-down\"></i>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t<div class=\"dropdown-content\">\r\n");
      out.write("\t\t\t\t<a href=\"addByEmail.html\">Fetch By Email-Id</a>\r\n");
      out.write("       \t\t\t<a href=\"addByPhone.html\">Fetch By Phone-Number</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"dropdown\">\r\n");
      out.write("\t\t\t<button class=\"dropbtn\">\r\n");
      out.write("\t\t\t\tGenerate Report <i class=\"fa fa-caret-down\"></i>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t<div class=\"dropdown-content\">\r\n");
      out.write("\t\t\t\t<a href=\"generateByEmail.html\">Fetch By Email-ID</a>\r\n");
      out.write("\t\t\t\t<a href=\"generateByPhone.html\">Fetch By Phone-Number</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<a href=\"#news\" style=\"float: right\">Exit</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t<form action=\"GenerateByEmail\" method=\"get\">\r\n");
      out.write("\t\tEnter Your Email: <input type=\"text\" name=\"email\" required><br>\r\n");
      out.write("\t\tEnter Date: <input type=\"text\" name=\"date\"> <input\r\n");
      out.write("\t\t\ttype=\"submit\" value=\"Submit\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<!-- <form action=\"InsertByEmail\" method=\"post\">\r\n");
      out.write("  <fieldset>\r\n");
      out.write("  <p>Enter Your Email: <input type=\"text\" name=\"email\"  required=\"required\" autofocus></p><br>\r\n");
      out.write("    <p>\r\n");
      out.write("      <input type=\"checkbox\" id=\"ecg\" name=\"testname\" value=\"ECG\">\r\n");
      out.write("      <label for=\"ecg\">ECG</label>\r\n");
      out.write("    </p>\r\n");
      out.write("    <p>\r\n");
      out.write("      <input type=\"checkbox\" id=\"hba1c\" name=\"testname\" value=\"HBA1c\">\r\n");
      out.write("      <label for=\"hba1c\">HBA1c</label>\r\n");
      out.write("    </p>\r\n");
      out.write("    <p>\r\n");
      out.write("      <input type=\"checkbox\" id=\"blood\" name=\"testname\" value=\"Blood Group\">\r\n");
      out.write("      <label for=\"third\">I like strawberry</label>\r\n");
      out.write("    </p>\r\n");
      out.write("  </fieldset>\r\n");
      out.write("</form> -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
